#!/usr/bin/env sh

RMPC="/run/current-system/sw/bin/rmpc"
JQ="/usr/bin/jq"

sticker=$("$RMPC" sticker get "$FILE" "playCount" 2>/dev/null | "$JQ" -r '.value // empty')

if [ -z "$sticker" ] || [ "$sticker" = "null" ]; then
    "$RMPC" sticker set "$FILE" "playCount" "1"
else
    "$RMPC" sticker set "$FILE" "playCount" "$((sticker + 1))"
fi
