music_directory     "~/Documents/mirror/Pleasure/Songs/"
playlist_directory  "~/dotfiles/.config/mpd/playlists"
db_file             "~/dotfiles/.config/mpd/database"
log_file            "~/dotfiles/.config/mpd/log"
pid_file            "~/dotfiles/.config/mpd/pid"
state_file          "~/dotfiles/.config/mpd/state"

#audio_output {
#  type "coreaudio"
#  name "macOS Audio"
#}
# Replace the coreaudio section with:
audio_output {
    type        "ao"
    name        "LibAO"
    device      "default"
}

bind_to_address "127.0.0.1:6600"

