music_directory     "/Users/gravity/Documents/mirror/Pleasure/Songs/"
playlist_directory  "/Users/gravity/dotfiles/.config/mpd/playlists"
db_file             "/Users/gravity/dotfiles/.config/mpd/database"
log_file            "/Users/gravity/dotfiles/.config/mpd/log"
pid_file            "/Users/gravity/dotfiles/.config/mpd/pid"
state_file          "/Users/gravity/dotfiles/.config/mpd/state"
sticker_file        "/Users/gravity/dotfiles/.config/mpd/sticker.sql"

audio_output {
    type        "osx"
    name        "CoreAudio"
}

bind_to_address "127.0.0.1:6600"

